name: 🎮 Godot Create Build
description: 🔨 Builds Godot project for specified platform

inputs:
  godot-version:
    description: '🔢 Godot version to use'
    required: true
    default: '4.3'
  export-name:
    description: '📝 Name of the exported file'
    required: true
  build-type:
    description: '🏗️ Build type (debug/release)'
    required: false
    default: 'debug'
  project-path:
    description: '📁 Path to the Godot project'
    required: false
    default: '.'

runs:
  using: docker
  image: barichello/godot-ci:${{ inputs.godot-version }}
  steps:
    - name: 🛠️ Setup Environment
      shell: bash
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mkdir -v -p ~/.config/
        mv /root/.config/godot ~/.config/godot
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
    
    - name: 🔨 Build Game
      shell: bash
      run: |
        mkdir -v -p build/windows
        EXPORT_DIR="$(readlink -f build)"
        cd ${{ inputs.project-path }}
        godot --headless --verbose --export-${{ inputs.build-type }} "Windows Desktop" "$EXPORT_DIR/windows/${{ inputs.export-name }}.exe"
